### ISSUE TITLE
Building with z88dk 2.3

### ISSUE THREAD

**Issue by mquin** [StalePixels/QEtoo#1]
I was looking to rebuild QE and ran into a couple of stumbling blocks with z88dk 2.3 (v22110-51889e5300-20231220) on MacOS.

The first is that -preserve doesn't seem to be a supported switch, and zcc tries to interpret it as a source file:

```
zcc +zxn -vn -O3 -startup=1 -clib=new -preserve -pragma-include:zpragma.inc -c    \
		--codesegBANK_47 --constsegBANK_47 \
		--datasegBANK_47 --bsssegBANK_47   \
		qe_banked.c -o./TMP/qe_banked.o
Unknown option2 -preserve
Cannot open source file: -preserve
make: *** [bank_47] Error 1
```
Removing that switch allows the build to proceed as far as the assemble stage, which fails to find QE_BANK_47.bin:

```
zxn: Error: Can't open "./TMP/QE_BANK_47.bin"
Page 95, allocate and loadBuilding application code failed
make: *** [assemble] Error 1
```

I've found that removing --clean from CZFLAGS allows the build to complete and the resulting QE binary works on the Next.

**Comment by Xalior** [comment]
100% correct, this default behaviour changed between 2.1 and 2.2, please
feel free to submit a pull request, and I’ll get it merged in (although I
won’t update the build on the distro, there’s no harm in the code remaining
ever green <3 )

**Comment by Xalior** [comment]
Pull request already here. You’re **too** good, Mike! x
